Fix FBGEMM Embedding Benchmark runtime errors
Update PyTorch from 2.7.0 to 2.8.0 to resolve runtime issues observed
during the FBGEMM Embedding Benchmark run.

Error log:

./benchpress_cli.py -b ai run fbgemm_embedding_a_single
stderr:
    Traceback (most recent call last):
      File "tbe_inference_benchmark.py", line 26, in <module>
    ModuleNotFoundError: No module named
'fbgemm_gpu.split_embedding_configs'
    [PYI-265070:ERROR] Failed to execute script
'tbe_inference_benchmark' due to unhandled exception!