Fix “Too many open files” (OSError 24) in multi-copy benchmark
Running benchmarks with a large number of copies can trigger:
 OSError: [Errno 24] Too many open files.

Example command:
(fbgemm_gpu_env)$ ulimit -n 1048576
(fbgemm_gpu_env)$ python ./bench/tbe/tbe_inference_benchmark.py nbit-cpu
\
    --num-embeddings=40000000 --bag-size=2 --embedding-dim=96 \
    --batch-size=162 --num-tables=8 --weights-precision=int4 \
    --output-dtype=fp32 --copies=96 --iters=30000

Cherry-pick the latest upstream commit from the FBGEMM main branch to
fix this issue.
This patch enables switching to the file_system sharing strategy via:
  export PYTORCH_SHARE_STRATEGY='file_system'